workflows:
  zilago-apk:
    name: ZilaGo APK
    instance_type: mac_mini_m2
    max_build_duration: 90
    environment:
      node: 22.13.0
      java: 17
    scripts:
      - name: Install
        script: |
          npm install --legacy-peer-deps
          npm install -g eas-cli
      - name: Build APK without native folder
        script: |
          eas build --platform android --profile preview --local --non-interactive --output ${CM_BUILD_DIR}/ZilaGo.apk
    artifacts:
      - ZilaGo.apk
